import Link from 'next/link';
import { Download } from 'lucide-react';
import raw from '../../../public/data/manifest.json';
import { releaseDate } from '@/lib/data';
import type { Manifest } from '@/lib/types';
const manifest = raw as unknown as Manifest;
export const metadata = { title: 'Sources & methodology · Agriculture Radar' };
export default function Methodology() {
  return <><header className="site-header"><Link href="/" className="brand"><span className="brand-mark" aria-hidden="true"/><span>Agriculture <strong>Radar</strong></span></Link><nav aria-label="Main navigation"><Link href="/">Explore</Link><Link href="/methodology/" className="active">Methodology</Link></nav><span className="header-note">FAOSTAT · World Bank</span></header><main className="methodology"><span className="eyebrow">Sources & methodology</span><h1>Every number has a source.</h1><p className="intro">Agriculture Radar combines annual crop production with monthly traded benchmark prices. The map covers wheat, maize, and rice. Each layer retains its own units, reference period, publication date, and provider flags.</p>
    <section><h2>What the map measures</h2><div className="table-scroll"><table><thead><tr><th>Layer</th><th>Unit</th><th>Definition</th></tr></thead><tbody><tr><td>Production</td><td>Tonnes</td><td>FAOSTAT annual crop production. Wheat and maize refer to dry grain; rice refers to paddy, before milling.</td></tr><tr><td>Yield</td><td>Tonnes / hectare</td><td>Provider yield converted from kg/ha by dividing by 1,000. Historical hg/ha values, if present, are divided by 10,000.</td></tr><tr><td>Production change</td><td>Percent</td><td>Selected-year production divided by mean production in the preceding five years, minus one, multiplied by 100. All five years and a positive baseline mean are required.</td></tr></tbody></table></div><p>A reported zero is a value. An absent observation is unavailable and appears grey. Regional aggregates and retired geographies are excluded using an explicit UN M49 to current ISO country/territory crosswalk.</p><p>Country shares use the sum of covered country and territory observations for the same crop and year. They are labelled shares of covered production; they are not presented as complete official world totals. Natural Earth’s small-scale boundaries omit some small countries and territories, which remain available in the country menu. Boundaries are a geographic display, not an assertion of political status.</p></section>
    <section><h2>Reference periods and releases</h2><div className="release-grid">{(['faostat', 'worldbank'] as const).map(key => { const r = manifest.releases[key]; return <div className="release-tile" key={key}><h3>{key === 'faostat' ? 'FAOSTAT crop production' : 'World Bank Pink Sheet'}</h3><p>Published {releaseDate(r.published_at)}<br/>Retrieved {releaseDate(r.first_seen_at)}</p><p><a href={r.source_url} target="_blank" rel="noreferrer">Provider dataset</a> · <a href={r.download_url} target="_blank" rel="noreferrer">Original file</a></p></div>; })}</div><p>The production reference year currently ends in 2024. Price observations currently end in September 2026. A snapshot retrieved today does not make historical observations current measurements. FAOSTAT’s publication date is the catalogue dataset-update date; the price publication date is read from the workbook. Neither supplies a separate publication timestamp for every historical row.</p><p>Raw files are archived with SHA-256 checksums. Normalized Parquet observations, release metadata, and geography are saved in immutable vintages. The JSON shown here is generated from one such vintage. Unknown publication dates remain unknown; retrieval dates are recorded separately.</p></section>
    <section><h2>Observation quality</h2><p>FAOSTAT’s flags are preserved. Country metrics show the production flag; the source drawer and CSV include flags for all metrics.</p><div className="table-scroll"><table><thead><tr><th>Flag</th><th>Meaning</th></tr></thead><tbody>{Object.entries(manifest.flags).map(([flag, meaning]) => <tr key={flag}><td>{flag}</td><td>{meaning}</td></tr>)}</tbody></table></div><p>Estimated and imputed observations are included with their flags. Unreported values are not filled by this pipeline. Historical country boundaries and coverage change; current-country histories do not silently inherit predecessor-state totals.</p></section>
    <section><h2>Prices are distinct from production</h2><p>The World Bank series are monthly nominal USD per metric tonne, with their published grades and market locations. They describe traded commodity benchmarks, not national farm-gate prices, household food prices, or producer margins.</p>{Object.entries(manifest.commodities).map(([key, c]) => <div key={key}><h3>{c.benchmark_name}</h3><p>{c.benchmark_description ?? c.benchmark_name}</p></div>)}<p>Historical specifications can change within a provider series. Missing cells are omitted and charts do not draw a line across missing months. Paddy-rice production and milled-rice prices have different product definitions and are not used to infer a revenue figure.</p></section>
    <section id="forecasts"><h2>Experimental benchmark forecasts</h2><p>The optional forecast overlay shows six monthly benchmark-price predictions and an 80% prediction band. A separate forecasting project consumes the saved price observations and publishes selected output only. Forecasts do not estimate country yields, crop supply, farmer profits, or retail inflation.</p><p>Candidate statistical forecasts are compared with a last-observation baseline. Selection and interval calibration use earlier rolling windows; final evaluation uses later, separate windows. Errors are assessed by MAE, RMSE, quantile loss, and empirical interval coverage. Forecast bands are calibrated separately for each horizon and preserve positive prices.</p><div className="notice"><p><strong>Revised-history evaluation.</strong> The current evaluation uses the historical values in today’s provider release. It does not reconstruct what was available at every historical forecast date. Archived vintages are being collected for future evaluations. The bands describe historical forecast errors and do not guarantee their stated coverage in future markets.</p></div><p>The interface labels these forecasts experimental. Where validation or calibration is unavailable, the pipeline omits that crop from published coverage. Forecasts are never summed across crops, and individual interval endpoints are not combined into an aggregate band.</p></section>
    <section><h2>Downloads and attribution</h2><p>Production CSVs include normalized values, original provider values and units, quality flags, and release identifiers. Prices are supplied separately. These downloads contain observations, not private forecasting methods.</p><div className="download-links">{Object.entries(manifest.commodities).map(([crop, c]) => <a key={crop} className="button" href={`/data/downloads/${crop}-production.csv`} download><Download size={15}/>{c.name} production</a>)}</div><p><a href="/data/manifest.json" download>Download the complete source manifest</a></p><p>FAOSTAT data: <a href={manifest.releases.faostat.license_url} target="_blank" rel="noreferrer">FAO data terms and attribution</a>. World Bank data: <a href={manifest.releases.worldbank.license_url} target="_blank" rel="noreferrer">dataset terms</a>, including commodity-specific third-party attribution in the workbook. Natural Earth boundaries are <a href={manifest.releases.geography.source_url} target="_blank" rel="noreferrer">public domain</a>.</p></section>
    <section><h2>Scope of this release</h2><p>This release implements the crop-production explorer and benchmark-price pipeline. Import dependence, bilateral trade flows, USDA supply estimates, crop-area-weighted weather risk, and environmental footprints require additional adapters and accounting validation. They are not inferred from the current production map.</p><p>Snapshot: {manifest.vintage}</p></section>
  </main></>;
}
